site_name: SmallRye Mutiny
repo_url: https://github.com/smallrye/smallrye-mutiny
docs_dir: docs/mkdocs
edit_uri: edit/main/docs/

nav:
  - 'index.md'
  - 'Tutorials':
      - 'tutorials/getting-started-with-mutiny.md'
      - 'tutorials/creating-uni-pipelines.md'
      - 'tutorials/creating-multi-pipelines.md'
      - 'tutorials/observing-events.md'
      - 'tutorials/transforming-items.md'
      - 'tutorials/transforming-items-asynchronously.md'
      - 'tutorials/handling-failures.md'
      - 'tutorials/retrying.md'
  - 'Topic guides':
      - 'topic-guides/imperative-to-reactive.md'
      - 'topic-guides/reactive-to-imperative.md'
      - 'topic-guides/unchecked-exceptions.md'
      - 'topic-guides/filtering-items.md'
      - 'topic-guides/collecting-items.md'
      - 'topic-guides/take-skip-items.md'
      - 'topic-guides/eliminate-duplicates-and-repetitions.md'
      - 'topic-guides/handling-null.md'
      - 'topic-guides/handling-timeouts.md'
      - 'topic-guides/delaying-events.md'
      - 'topic-guides/pagination.md'
      - 'topic-guides/polling.md'
      - 'topic-guides/emission-threads.md'
      - 'topic-guides/emit-on-vs-run-subscription-on.md'
      - 'topic-guides/completion-stage.md'
      - 'topic-guides/rx.md'
      - 'topic-guides/shortcut-methods.md'
      - 'topic-guides/merging-and-concatenating-streams.md'
      - 'topic-guides/combining-items.md'
      - 'topic-guides/joining-unis.md'
      - 'topic-guides/converters.md'
      - 'topic-guides/testing.md'
      - 'topic-guides/custom-operators.md'
      - 'topic-guides/dropped-exceptions.md'
      - 'topic-guides/framework-integration.md'
      - 'topic-guides/hot-streams.md'
      - 'topic-guides/integrate-a-non-reactive-source.md'
      - 'topic-guides/kotlin.md'

theme:
  name: material
  logo: assets/logo.png
  font:
    text: Roboto
    code: JetBrains Mono
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - toc:
      permalink: '#'
  - admonition
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - macros:
      verbose: true
      module_name: docs/mkdocs-customizations/macros/docissimo
      include_dir: docs/mkdocs-customizations/macros

extra:
  snippet_dir: docs/src/test
  attributes_path: docs/attributes.yaml
  javadoc_artifact: io.smallrye.reactive/smallrye-mutiny